import { createClient } from "@/lib/supabase/server";
import { NextResponse } from "next/server";

export async function POST(
  request: Request,
  { params }: { params: Promise<{ id: string }> },
) {
  try {
    const { id: groupId } = await params;
    const supabase = await createClient();

    const {
      data: { user },
    } = await supabase.auth.getUser();
    if (!user)
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    const body = await request.json();
    const email =
      typeof body.email === "string" ? body.email.trim().toLowerCase() : "";

    if (!email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      return NextResponse.json(
        { error: "A valid email is required" },
        { status: 400 },
      );
    }

    // Confirm current user is a group member
    const { data: memberCheck } = await supabase.rpc("is_group_member", {
      _group_id: groupId,
      _user_id: user.id,
    });
    if (!memberCheck) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    // Fetch group name for invite text
    const { data: group } = await supabase
      .from("groups")
      .select("name")
      .eq("id", groupId)
      .single();
    const groupName = group?.name ?? "the group";

    // CASE A: email is already registered
    const { data: profile } = await supabase
      .from("profiles")
      .select("id, full_name, email, avatar_color")
      .eq("email", email)
      .single();

    if (profile) {
      // Check not already a member
      const { data: existing } = await supabase
        .from("group_members")
        .select("user_id")
        .eq("group_id", groupId)
        .eq("user_id", profile.id)
        .single();

      if (existing) {
        return NextResponse.json(
          { error: "Already a member" },
          { status: 400 },
        );
      }

      const { error: insertError } = await supabase
        .from("group_members")
        .insert({ group_id: groupId, user_id: profile.id });

      if (insertError) {
        return NextResponse.json(
          { error: insertError.message },
          { status: 500 },
        );
      }

      return NextResponse.json(
        {
          status: "added",
          member: {
            id: profile.id,
            fullName: profile.full_name ?? null,
            email: profile.email,
            avatarColor: profile.avatar_color,
          },
        },
        { status: 201 },
      );
    }

    // CASE B: email not yet registered
    // Check not already pending in this group
    const { data: existingPending } = await supabase
      .from("pending_members")
      .select("id")
      .eq("email", email)
      .single();

    if (existingPending) {
      const { data: alreadyInGroup } = await supabase
        .from("group_pending_members")
        .select("pending_member_id")
        .eq("group_id", groupId)
        .eq("pending_member_id", existingPending.id)
        .single();

      if (alreadyInGroup) {
        return NextResponse.json({ error: "Already invited" }, { status: 400 });
      }
    }

    // Upsert pending_members (email is UNIQUE — ignore duplicate on conflict)
    await supabase
      .from("pending_members")
      .upsert(
        { email, invited_by: user.id },
        { onConflict: "email", ignoreDuplicates: true },
      );

    const { data: pendingMember } = await supabase
      .from("pending_members")
      .select("id")
      .eq("email", email)
      .single();

    if (!pendingMember) {
      return NextResponse.json(
        { error: "Failed to create pending member" },
        { status: 500 },
      );
    }

    // Insert into group_pending_members
    const { error: gpmError } = await supabase
      .from("group_pending_members")
      .insert({
        group_id: groupId,
        pending_member_id: pendingMember.id,
        invited_by: user.id,
      });

    if (gpmError) {
      return NextResponse.json({ error: gpmError.message }, { status: 500 });
    }

    // Insert invitation (token generated by DB DEFAULT)
    const { error: invError } = await supabase.from("invitations").insert({
      email,
      group_id: groupId,
      pending_member_id: pendingMember.id,
      invited_by: user.id,
    });

    if (invError) {
      return NextResponse.json({ error: invError.message }, { status: 500 });
    }

    // Fetch the token just inserted
    const { data: invitation } = await supabase
      .from("invitations")
      .select("token")
      .eq("pending_member_id", pendingMember.id)
      .eq("group_id", groupId)
      .is("accepted_at", null)
      .order("created_at", { ascending: false })
      .limit(1)
      .single();

    if (!invitation) {
      return NextResponse.json(
        { error: "Failed to retrieve invitation" },
        { status: 500 },
      );
    }

    const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? "";
    const inviteUrl = `${siteUrl}/invite/${invitation.token}`;
    const inviteText = `Hey! I've added you to "${groupName}" on SplitMate so we can track our shared expenses together.\n\nSign in here to see your balance:\n${inviteUrl}`;

    return NextResponse.json({
      status: "pending",
      pendingMember: { id: pendingMember.id, email },
      inviteToken: invitation.token,
      inviteUrl,
      inviteText,
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Failed to add member";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
